version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3200
      MYSQL_DATABASE: project
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql